version: "3"
networks:
    db_net:
        driver: bridge

services:
    db:
        image: mongo:latest
        command: mongod --smallfiles
        networks:
            - db_net

    api:
        build: .
        depends_on: 
            - db
        ports:
            - 8080:8080
        environment:
            - MONGODB_NAME=test
        networks:
            - db_net
